### ISSUE TITLE
RaptorRoute does not have public getters

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#17]
`RaptorRoute` does not really have public getters. This is especially tricky when one uses 

`public List<RaptorRoute> calcRoutes(Facility<?> fromFacility, Facility<?> toFacility, double earliestDepartureTime, double desiredDepartureTime, double latestDepartureTime, Person person)`

to obtain a List of options during a certain time span. In my specific use case I would like to use this to calculate the frequency of a certain connection. However, the way it is structured right now I cannot find out if a route consists of "only walk" or not ... 

Three possible solutions:
- Make the members of `RaptorRoute` `public` since they are `final` anway.
- Add getters for the members variables of `RaptorRoute`
- Circumvent the issue by making `calcRoutes` `private` and add a new method like `calcRoutes`, which returns a `List<List<Leg>>` where the routes are already converted to `Leg`s

What do you prefer? :)

**Comment by mrieser** [comment]
Since about a month, RaptorRoute has additional methods, i.e. `getParts()` which returns you additional information that should help you answer your questions. It is available in the 0.11.0-SNAPSHOT in my branch.
As an alternative, you could convert the RaptorRoute to Legs with RaptorUtils.convertRouteToLegs, although that comes with some overhead.

**Comment by sebhoerl** [comment]
Thanks!
