### ISSUE TITLE
Improvement for findNearbyStops 

### ISSUE THREAD

**Issue by sebhoerl** [SchweizerischeBundesbahnen/matsim-sbb-extensions#5]
As far as I see the algorithm

1. Finds all the stops within `searchRadius`
2. If only one or none has been found
   - Find the closest stop
   - Find the all the stops around that one within `searchRadius + extensionRadius`

Is there a specific reason why it is done like that? Wouldn't it make sense to extend the functionality of the quadtree to give "n nearest objects", and then only define a `numberOfStopsToConsider` for the router? Or maybe a combination of `numberOfStopsToConsider` and `searchRadius`, i.e. if the latter doesn't give enough of results, continue with the former?

**Comment by manserpa** [comment]
I assume that the main reason for this design was using as many standard MATSim parameters as possible and extending it by only few specific raptor-parameters. 

What is your use-case for this feature? I’m not perfectly sure whether it is a good idea or not. If the closest stop is very far away, the router must calculate many (in this case `numberOfStopsToConsider`) bad routes which results in a performance loss. Setting a `maxSearchRadius` would be even one parameter more. On the other hand, there are certainly cases where it makes sense to have a combination of `numberOfStopsToConsider` and `searchRadius`. I could image that it might become a quite interesting approach in the case of intermodal applications, because it is not very clear how to set a `searchRadius` for a taxi mode.

We don't have an urgent use-case for this at the moment, so it has no high priority on our todo-list.
Feel free to open a pull request with your extension of the code, if you have any good idea how to implement it.

**Comment by sebhoerl** [comment]
I was just wondering, because it is not a really straightforward way of searching for stops :) And doesnt the routing to very far stops happen anyway with the current version (in stage (2)).
